// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SongsTracker.Data.Database;

#nullable disable

namespace SongsTracker.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    partial class TrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("SongsTracker.Data.Models.UniqueArtistsModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UniqueArtists");
                });

            modelBuilder.Entity("SongsTracker.Data.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UniqueArtistsModelUserModel", b =>
                {
                    b.Property<long>("FollowersId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TrackedArtistsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FollowersId", "TrackedArtistsId");

                    b.HasIndex("TrackedArtistsId");

                    b.ToTable("UniqueArtistsModelUserModel");
                });

            modelBuilder.Entity("UniqueArtistsModelUserModel", b =>
                {
                    b.HasOne("SongsTracker.Data.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("FollowersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SongsTracker.Data.Models.UniqueArtistsModel", null)
                        .WithMany()
                        .HasForeignKey("TrackedArtistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
